---
# tasks file for vagrant_env


- name: Install pre-requisite docker package
  yum:
    name: ['device-mapper-persistent-data', 'lvm2', 'yum-utils']
    state: latest  

# - name: upgrade all packages
#   yum: name=* state=latest

- name: Add repository for pip
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: install pip
  yum:
    name: python-pip
    state: latest
    disable_gpg_check: yes

- pip:
    name: docker


- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes


- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes