---

- name: copy daemon.json
  template: 
    src: daemon.json
    dest: /etc/docker

- name: create folder for override.conf
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy override.conf
  template:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

# - name: Restart docker
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: docker