---
# tasks file for vagrant_env

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: create directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Expose Api 
  command: "{{ item }}"
  with_items:
    - printf "[Service]\nExecStart=\nExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376 -H unix://var/run/docker.sock" | tee /etc/systemd/system/docker.service.d/expose.conf
    - systemctl daemon-reload
    - systemctl restart docker